# Statistical Tests Configuration

feature_sets:

  tasks_completed:
    - total_tasks_1_10
    - total_tasks_11_25
    - total_tasks_26_75
    - total_tasks_76_125
    - total_tasks_126_175
    - total_tasks_176_225
    - total_tasks_226_plus

  # Cumulative bins (overlapping)
  # days_active_cumulative:
    # - days_active_<2
    # - days_active_<10
    # - days_active_<20
    # - days_active_<30
    # - days_active_<50
    # - days_active_<75
    # - days_active_<100
    # - days_active_<125
    # - days_active_<150
    # - days_active_<200
    # - days_active_<250
    # - days_active_>=250

# Mutually exclusive bins
  days_active_exclusive:
    - days_active_0_to_2
    - days_active_3_to_10
    - days_active_11_to_20
    - days_active_21_to_30
    - days_active_31_to_50
    - days_active_51_to_75
    - days_active_76_to_100
    - days_active_101_to_125
    - days_active_126_to_150
    - days_active_151_to_200
    - days_active_201_to_250
    - days_active_251_plus

  temporal_day_of_week:
    - is_weekend
    - is_monday
    - is_tuesday
    - is_wednesday
    - is_thursday
    - is_friday
    - is_saturday
    - is_sunday

  temporal_business_hours:
    - is_business_hour
    - is_business_hour_weekday
    - is_business_hour_weekend

  temporal_time_of_day:
    - is_early_morning
    - is_morning
    - is_afternoon
    - is_evening
    - is_night

  temporal_hourly:
    - is_12am
    - is_1am
    - is_2am
    - is_3am
    - is_4am
    - is_5am
    - is_6am
    - is_7am
    - is_8am
    - is_9am
    - is_10am
    - is_11am
    - is_12pm
    - is_1pm
    - is_2pm
    - is_3pm
    - is_4pm
    - is_5pm
    - is_6pm
    - is_7pm
    - is_8pm
    - is_9pm
    - is_10pm
    - is_11pm

  task_speed:
    - is_suspiciously_fast
    - is_very_fast
    - is_fast
    - is_normal_speed
    - is_slow
    - is_suspiciously_slow

  # quality:
  #   - quality=100
  #   - quality<90
  #   - quality<75
  #   - quality<50
  #   - quality<30

  # risk:
  #   - risk=100
  #   - risk<90
  #   - risk<80
  #   - risk<50

  gender:
    - gender_female
    - gender_male
    - gender_other
    - gender_prefer not to say

  income:
    - "fulcrum_household_income_mapped_Less than £15,000"
    - "fulcrum_household_income_mapped_£15,000 to £19,999"
    - "fulcrum_household_income_mapped_£20,000 to £24,999"
    - "fulcrum_household_income_mapped_£25,000 to £29,999"
    - "fulcrum_household_income_mapped_£30,000 to £34,999"
    - "fulcrum_household_income_mapped_£35,000 to £39,999"
    - "fulcrum_household_income_mapped_£40,000 to £44,999"
    - "fulcrum_household_income_mapped_£45,000 to £49,999"
    - "fulcrum_household_income_mapped_£50,000 to £59,999"
    - "fulcrum_household_income_mapped_£60,000 to £74,999"
    - "fulcrum_household_income_mapped_£75,000 to £84,999"
    - "fulcrum_household_income_mapped_£85,000 to £99,999"
    - "fulcrum_household_income_mapped_£100,000 to £124,999"
    - "fulcrum_household_income_mapped_£125,000 to £149,999"
    - "fulcrum_household_income_mapped_£150,000 to £174,999"
    - "fulcrum_household_income_mapped_£175,000 to £199,999"
    - "fulcrum_household_income_mapped_£200,000 and above"
    - "fulcrum_household_income_mapped_Prefer not to answer"
    - fulcrum_household_income_mapped_nan

  gambling:
    - gambling_participation_mc_bingo
    - "gambling_participation_mc_car race betting"
    - "gambling_participation_mc_casino poker"
    - "gambling_participation_mc_casino slot machines"
    - "gambling_participation_mc_do not gamble at all"
    - "gambling_participation_mc_horse track betting"
    - "gambling_participation_mc_offline lottery"
    - "gambling_participation_mc_offline sports betting"
    - "gambling_participation_mc_online lottery"
    - "gambling_participation_mc_online poker"
    - "gambling_participation_mc_online sports betting"
    - gambling_participation_mc_other

  platform: # to replace
    - platform_name_Android
    - platform_name_iOS
    - platform_name_Linux
    - platform_name_Mac OS X
    - platform_name_Windows
    - platform_name_Unknown

  device: # to replace
    - device_Android
    - device_iOS
    - device_Windows
    - device_Linux
    - device_ChromeOS
    - device_Tizen
    - device_Unknown

  hardware: # to replace
    - hardware_version_iPhone
    - hardware_version_iPod Touch
    - hardware_version_Desktop
    - hardware_version_Macintosh
    - hardware_version_Baoxue
    - hardware_version_Fablet
    - hardware_version_G2
    - "hardware_version_Galaxy Note 4"
    - "hardware_version_Generic Android"
    - "hardware_version_IDOL 3 6045Y"
    - hardware_version_L9
    - "hardware_version_P8 Standard"
    - hardware_version_RocStar
    - hardware_version_ShotX
    - "hardware_version_Xperia E3 Dual"

  exposure:
    - exposure_band_control
    - exposure_band_exposed

  entry_point:
    - entryPoint_offerwall
    - entryPoint_notification

  email_verification:
    - email_verified_False
    - email_verified_True

  share_location_data:
    - share_location_data_False
    - share_location_data_True

  notify_new_task:
    - notify_new_task_False
    - notify_new_task_True

  notify_task_payout:
    - notify_task_payout_False
    - notify_task_payout_True

  ip_address_count:
    - ip_address_count_1
    - ip_address_count_2
    - ip_address_count_3
    - ip_address_count_4
    - ip_address_count_5

employer_industry:
    - employer_industry_mapped_Accounting
    - employer_industry_mapped_Advertising
    - employer_industry_mapped_Agriculture/Fishing
    - employer_industry_mapped_Architecture
    - employer_industry_mapped_Automotive
    - employer_industry_mapped_Aviation
    - employer_industry_mapped_Banking/Financial
    - employer_industry_mapped_Bio-Tech
    - employer_industry_mapped_Brokerage
    - employer_industry_mapped_Carpenting/Electrical installations/VVS
    - employer_industry_mapped_Chemicals/Plastics/Rubber
    - employer_industry_mapped_Communications/Information
    - employer_industry_mapped_Computer Hardware
    - employer_industry_mapped_Computer Reseller (software/hardware)
    - employer_industry_mapped_Computer Software
    - employer_industry_mapped_Construction
    - employer_industry_mapped_Consulting
    - employer_industry_mapped_Consumer Electronics
    - employer_industry_mapped_Consumer Packaged Goods
    - employer_industry_mapped_Education
    - employer_industry_mapped_Energy/Utilities/Oil and Gas
    - employer_industry_mapped_Engineering
    - employer_industry_mapped_Environmental Services
    - employer_industry_mapped_Fashion/Apparel
    - employer_industry_mapped_Food/Beverage
    - employer_industry_mapped_Government/Public Sector
    - employer_industry_mapped_Healthcare
    - employer_industry_mapped_Hospitality/Tourism
    - employer_industry_mapped_Human Resources
    - employer_industry_mapped_I don't work
    - employer_industry_mapped_Information Technology/IT
    - employer_industry_mapped_Insurance
    - employer_industry_mapped_Internet
    - employer_industry_mapped_Legal/Law
    - employer_industry_mapped_Manufacturing
    - employer_industry_mapped_Market Research
    - employer_industry_mapped_Marketing/Sales
    - employer_industry_mapped_Media/Entertainment
    - employer_industry_mapped_Military
    - employer_industry_mapped_Non Profit/Social services
    - employer_industry_mapped_Other
    - employer_industry_mapped_Personal Services
    - employer_industry_mapped_Pharmaceuticals
    - employer_industry_mapped_Printing Publishing
    - employer_industry_mapped_Public Relations
    - employer_industry_mapped_Real Estate/Property
    - employer_industry_mapped_Retail/Wholesale trade
    - employer_industry_mapped_Security
    - employer_industry_mapped_Shipping/Distribution
    - employer_industry_mapped_Telecommunications
    - employer_industry_mapped_Transportation
    - employer_industry_mapped_nan

employer_department:
    - employer_department_mapped_Administration/General Staff
    - employer_department_mapped_Customer Service/Client Service
    - employer_department_mapped_Executive Leadership
    - employer_department_mapped_Finance/Accounting
    - employer_department_mapped_Human Resources
    - employer_department_mapped_I don't work
    - employer_department_mapped_Legal/Law
    - employer_department_mapped_Marketing
    - employer_department_mapped_Operations
    - employer_department_mapped_Other
    - employer_department_mapped_Procurement
    - employer_department_mapped_Sales/Business Development
    - employer_department_mapped_Technology Development Hardware (not only IT)
    - employer_department_mapped_Technology Development Software (not only IT)
    - employer_department_mapped_Technology Implementation
    - employer_department_mapped_nan

 region:
    - fulcrum_region_mapped_East Midlands (England)
    - fulcrum_region_mapped_East Of England
    - fulcrum_region_mapped_London
    - fulcrum_region_mapped_North East (England)
    - fulcrum_region_mapped_North West (England)
    - fulcrum_region_mapped_Northern Ireland
    - fulcrum_region_mapped_Scotland
    - fulcrum_region_mapped_South East (England)
    - fulcrum_region_mapped_South West (England)
    - fulcrum_region_mapped_Wales
    - fulcrum_region_mapped_West Midlands (England)
    - fulcrum_region_mapped_Yorkshire And The Humber
    - fulcrum_region_mapped_nan

test_settings:
  significance_level: 0.05
  bonferroni_correction: true
  outcome_var: "wonky_study_count"
  user_id_var: "respondentPk"
  min_sample_size: 30

feature_groups:
  behavioral:
    - tasks_completed
    - days_active_cumulative
    - days_active_exclusive
    - task_speed
    - entry_point

  temporal:
    - temporal_day_of_week
    - temporal_business_hours
    - temporal_time_of_day

  demographic:
    - gender
    - income
    - region
    - employer_industry
    - employer_department

  platform:
    - platform
    - device
    - hardware

  user_settings:
    - email_verification
    - share_location_data
    - notify_new_task
    - notify_task_payout

  quality_risk:
    - quality
    - risk

  experimental:
    - exposure