# Wonky Studies Configuration

# List of wonky study UUIDs
wonky_study_uuids:
  - "8a918182-9da2-4272-b51e-57b9ca8f5253"
  - "08172f99-f0c6-4690-9585-f54bf140bbb4"
  - "d782681c-c976-428e-9795-6d378887601b"
  - "1b67a8fb-fb84-404b-be19-a87371f564b7"
  - "2f13bb68-cf8d-447e-ae5b-cf4e4de3322e"
  - "99a6f654-d253-411c-8b3d-22adb15bf703"
  - "f1cffb37-ad0f-402a-9f8e-7498f9bea2bf"
  - "b520dd37-d2ba-4e26-bff7-592af2dae30f"
  - "f7422d22-b25d-4a1b-9a20-b7bf614ef303"
  - "81a68a08-9e0a-4287-b3bf-ae2a4a23af46"
  - "2bba4596-ae91-4475-ac7d-ed2c0c262594"
  - "5290c135-c6cb-4e0d-ab1e-1b29aa293de9"
  - "076dcdae-c23a-448f-b140-c925f1ecd4fc"
  - "eb545869-5900-4662-b116-af8a9944ee2c"
  - "960337ba-115d-45c2-a350-6c038ee92ea5"
  - "36089f7b-6c05-4110-a8e6-5cb53e8fb3f9"
  - "16a643a2-c77d-43ea-820a-1f96ba119075"
  - "6859295f-6e2e-4ad7-be7c-c370091ffbfc"
  - "ffbda696-9120-4e97-9f0d-8dc2a822359e"
  - "3237de05-9714-4c48-83e3-90fc938ff541"
  - "2aba6514-5418-42d3-b9f2-1ae002258721"
  - "cac701cc-e5ea-4e14-999c-e499928f878a"
  - "0db08dad-19f0-46cc-a246-2ac2ab17cc45"
  - "e42caae5-1b62-4983-ab49-d3c17b30ff7f"
  - "09de19bd-0d61-4b3b-9f34-c64ce5bf9e0d"
  - "e3cf1ebe-ea58-4f3d-a856-d68c7a19ddb5"
  - "7ddb40ca-3314-4249-b798-65c2da0d5957"
  - "092b40f2-b414-41d7-903f-ba1022ab4801"
  - "f3e4ccc6-d503-4ab4-82d1-9baff3ea538d"
  - "42710574-12eb-422a-a1ad-1053ae953dbe"
  - "26fe91ca-541f-4d0e-a4bd-a6b692a87ebb"
  - "7a6a07fd-1a4e-4c9e-b13a-d2468f038203"
  - "529f4761-a7bf-4171-9282-1e9f8ef4879b"
  - "ef8aaefb-801d-4f61-a34c-7da4340de818"
  - "88daec7d-4a5e-4629-be52-8658eba629eb"
  - "08842f4f-c056-4e1f-b982-401d3fbd776e"
  - "f218e979-ed7c-402b-b89e-3e4ffc0d6eed"

# Columns to include from balance tables
cols_to_include_subset:
  - "respondent_pk"
  - "survey_pk"
  - "platform_name"
  - "hardware_version"
  - "yob"
  - "survey_locale"
  - "request-remote-addr"
  - "user-agent"
  - "exposure_band"

# Columns to group by for aggregation
cols_to_group:
  - "respondent_pk"
  - "survey_pk"
  - "platform_name"
  - "hardware_version"
  - "yob"
  - "survey_locale"
  - "request-remote-addr"
  - "user-agent"
  - "exposure_band"
  - "task_pk"
  - "task_origin_id"
  - "task_length_of_task"
  - "task_country"
  - "task_targeting_type"
  - "task_category"
  - "task_points"
  - "activation_date"

# Columns to drop
cols_to_drop:
  - "id"
  - "version"
  - "amount"
  - "button_text"
  - "category"
  - "date_created"
  - "description"
  - "epc"
  - "field_end_date"
  - "expiry_date"
  - "for_android"
  - "for_ios"
  - "last_updated"
  - "link"
  - "origin"
  - "points"
  - "public_description"
  - "public_logo"
  - "public_title"
  - "ratio"
  - "status"
  - "last_task_query_id"
  - "title"
  - "workflow_description"
  - "rank"
  - "language"
  - "group_pk"
  - "reference_url"
  - "field_begin_date"
  - "additional"
  - "auto_deactivate"
  - "sequence_id"
  - "sequence_index"
  - "exchange_rate"
  - "margin"
  - "number_of_time_activated"
  - "workflow_type"
  - "Op"
  - "additional_map"
  - "buyer"
  - "unrepresented_quals"
  - "unrepresented_quota"

