# Wonky Studies Configuration

# List of wonky study UUIDs
wonky_study_uuids:
  "08172f99-f0c6-4690-9585-f54bf140bbb4": false
  "092b40f2-b414-41d7-903f-ba1022ab4801": true
  "09de19bd-0d61-4b3b-9f34-c64ce5bf9e0d": false
  "0db08dad-19f0-46cc-a246-2ac2ab17cc45": true
  "16a643a2-c77d-43ea-820a-1f96ba119075": false
  "1b67a8fb-fb84-404b-be19-a87371f564b7": false
  "2aba6514-5418-42d3-b9f2-1ae002258721": false
  "2bba4596-ae91-4475-ac7d-ed2c0c262594": true
  "2f13bb68-cf8d-447e-ae5b-cf4e4de3322e": true
  "3237de05-9714-4c48-83e3-90fc938ff541": false
  "36089f7b-6c05-4110-a8e6-5cb53e8fb3f9": false
  "42710574-12eb-422a-a1ad-1053ae953dbe": false
  "5290c135-c6cb-4e0d-ab1e-1b29aa293de9": true
  "529f4761-a7bf-4171-9282-1e9f8ef4879b": true
  "6859295f-6e2e-4ad7-be7c-c370091ffbfc": true
  "7a6a07fd-1a4e-4c9e-b13a-d2468f038203": true
  "7ddb40ca-3314-4249-b798-65c2da0d5957": true
  "81a68a08-9e0a-4287-b3bf-ae2a4a23af46": true
  "88daec7d-4a5e-4629-be52-8658eba629eb": true
  "8a918182-9da2-4272-b51e-57b9ca8f5253": true
  "960337ba-115d-45c2-a350-6c038ee92ea5": false
  "99a6f654-d253-411c-8b3d-22adb15bf703": false
  "b520dd37-d2ba-4e26-bff7-592af2dae30f": true
  "cac701cc-e5ea-4e14-999c-e499928f878a": false
  "d782681c-c976-428e-9795-6d378887601b": false
  "e3cf1ebe-ea58-4f3d-a856-d68c7a19ddb5": true
  "e42caae5-1b62-4983-ab49-d3c17b30ff7f": false
  "eb545869-5900-4662-b116-af8a9944ee2c": false
  "ef8aaefb-801d-4f61-a34c-7da4340de818": false
  "f1cffb37-ad0f-402a-9f8e-7498f9bea2bf": true
  "f218e979-ed7c-402b-b89e-3e4ffc0d6eed": false
  "f3e4ccc6-d503-4ab4-82d1-9baff3ea538d": true
  "f7422d22-b25d-4a1b-9a20-b7bf614ef303": false
  "ffbda696-9120-4e97-9f0d-8dc2a822359e": true

# Columns to include from balance tables
cols_to_include_subset:
  - "respondent_pk"
  - "survey_pk"
  - "platform_name"
  - "hardware_version"
  - "yob"
  - "survey_locale"
  - "request-remote-addr"
  - "user-agent"
  - "exposure_band"

# Columns to group by for aggregation
cols_to_group:
  - "respondent_pk"
  - "survey_pk"
  - "platform_name"
  - "hardware_version"
  - "yob"
  - "survey_locale"
  - "request-remote-addr"
  - "user-agent"
  - "exposure_band"
  - "task_pk"
  - "task_origin_id"
  - "task_length_of_task"
  - "task_country"
  - "task_targeting_type"
  - "task_category"
  - "task_points"
  - "activation_date"

# Columns to exclude from respondent_info table (reduces memory footprint)
cols_to_exclude_respondent_info:
  - "alcoholFrequency"
  - "alcohol_frequency"
  - "all_starts_last_30_days"
  - "auto_car_brand"
  - "auto_car_brand_mc"
  - "auto_car_future_purchase"
  - "auto_car_manufacture_date"
  - "auto_car_purchase_date"
  - "auto_car_purchase_type"
  - "auto_car_type"
  - "auto_car_type_mc"
  - "auto_decision_maker"
  - "auto_motorcycle_use"
  - "beverageRegularConsumption"
  - "beverage_regular_consumption_mc"
  - "beverage_p4w"
  - "beverage_p4w_mc"
  - "cellular_plan"
  - "children_age_and_gender"
  - "children_age_and_gender_mc"
  - "children_gender"
  - "children_in_household"
  - "children_number_in_household"
  - "children_yob"
  - "clothing_and_homeware_retailer"
  - "clothing_and_homeware_retailer_main"
  - "clothing_purchase"
  - "clothing_purchase_frequency"
  - "clothing_retailer_denim"
  - "clothing_retailer_denim_main"
  - "consumer_traits"
  - "ethnicity_hispanic"
  - "exercise_hours"
  - "exercise_hours_mc"
  - "eyewear"
  - "fastfood_frequency"
  - "fastfood_frequency"
  - "flight_destination"
  - "flight_destination_mc"
  - "flight_purpose"
  - "flight_use"
  - "grocery_shopper"
  - "hobbies"
  - "hobbies_mc"
  - "holiday_accommodation"
  - "home_improvement_category"
  - "home_improvement_retailers_kitchen"
  - "homeware_retailer"
  - "hotel_use"
  - "household_investable_assets"
  - "household_other_industry"
  - "household_other_industry_mc"
  - "household_pets"
  - "household_pets_mc"
  - "level_of_education"
  - "main_grocery_shop"
  - "malaysian_ethnicity"
  - "region"
  - "regionOther1"
  - "region_city_state"
  - "region_level1"
  - "region_level2" 
  - "region_level3"
  - "region_nuts1"

# Columns to drop
cols_to_drop:
  - "id"
  - "version"
  - "amount"
  - "button_text"
  - "category"
  - "date_created"
  - "description"
  - "epc"
  - "field_end_date"
  - "expiry_date"
  - "for_android"
  - "for_ios"
  - "last_updated"
  - "link"
  - "origin"
  - "points"
  - "public_description"
  - "public_logo"
  - "public_title"
  - "ratio"
  - "status"
  - "last_task_query_id"
  - "title"
  - "workflow_description"
  - "rank"
  - "language"
  - "group_pk"
  - "reference_url"
  - "field_begin_date"
  - "additional"
  - "auto_deactivate"
  - "sequence_id"
  - "sequence_index"
  - "exchange_rate"
  - "margin"
  - "number_of_time_activated"
  - "workflow_type"
  - "Op"
  - "additional_map"
  - "buyer"
  - "unrepresented_quals"
  - "unrepresented_quota"